version: '3.8'
services:
  nest-api:
    image: conservativ/nestjs-api-server:1.0.3
    ports:
      - 4000:4000
    command: sh -c "npx prisma migrate dev --name init && npm run start:prod"
    depends_on:
      - postgres
    env_file:
      - .env

  react-app:
    image: conservativ/nestjs-api-frontend:1.0.2
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - nest-api

  postgres:
    image: postgres:13
    container_name: postgres-api1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
